services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PASSWORD_SALT: ${PASSWORD_SALT:-default_salt}
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/mydatabase}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-default_jwt_secret}
      JWT_ISSUER: ${JWT_ISSUER:-luodingo}

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d mydatabase" ]
      interval: 1s

volumes:
  db_data:

